baseURL: "https://metarex.media"
title: "metarex.media"
theme: fohuw
contentDir: "content"

# override publishing to public so that ko can build a lightweight container
publishDir: kodata

enableRobotsTXT: true

# --- Menus -------------------------------------------------------------------
# uncomment this line to automatically generate a top level section menu
# keep the comment if you only want some of the top level menus to appear
# sectionPagesMenu: main

#   __  __          _
#  |  \/  |  __ _  (_)  _ _      _ __    ___   _ _    _  _
#  | |\/| | / _` | | | | ' \    | '  \  / -_) | ' \  | || |
#  |_|  |_| \__,_| |_| |_||_|   |_|_|_| \___| |_||_|  \_,_|
menus:
  main:
    - name: Technology
      identifier: tech
    - name: Specifications
      URL: /docs/specifications/
      parent: tech
      weight: 10
    - name: Case Studies
      URL: /docs/studies/
      parent: tech
      weight: 20
      identifier: specs
    - name: app/reg
      URL: /app/reg/
      parent: tech
      weight: 50
      identifier: appreg
    - name: app/demos
      URL: /app/demos/
      parent: tech
      weight: 51
      identifier: appdemos
  #                                   _ _     ___
  #   _ __    ___   _ _    _  _     _| | |_  |_  )
  #  | '  \  / -_) | ' \  | || |   |_  .  _|  / /
  #  |_|_|_| \___| |_||_|  \_,_|   |_     _| /___|
  #                                  |_|_|
  menu2:
    - name: MetaRex on Instagram 
      URL: https://www.instagram.com/metarex.media?igsh=MWNidHNudDB5MXlwMA==
      identifier: Instagram
      pre: '<i class="instagram icon"></i>'
      post: " 🦖"
      weight: 90
    - name: MetaRex on LinkedIn
      URL: https://www.linkedin.com/search/results/all/?keywords=%23metarex
      identifier: LinkedIn
      pre: '<i class="linkedin icon"></i>'
      post: " 🦖"
      weight: 100
    - name: MetaRex on GitHub
      URL: https://github.com/orgs/metarex-media/repositories?q=sort%3Aname-asc
      identifier: GitHub
      pre: '<i class="github icon"></i>'
      post: " 🦖"
      weight: 110

    # - name:       See the IBC Winner
    #   URL:        /donate/
    #   identifier: cake
    #   pre:
    #   post:       " 🦖"
    #   weight:     110
    - name: Feed Rexy
      URL: /donate/
      identifier: cake
      pre:
      post: " 🍰"
      weight: 110
    - name: Try a demo
      URL: /app/demos/
      identifier: feed
      pre:  "⏯️ "
      post: " 🦖"
      weight: 120
# links to linkedin left & right
  
  
  # Menu Rexy
  menurexy:
    - name: MetaRex on Instagram 
      URL: https://www.instagram.com/metarex.media?igsh=MWNidHNudDB5MXlwMA==
      identifier: Instagram
      pre: '<i class="instagram icon"></i>'
      post: " 🦖"
      weight: 90
    - name: MetaRex on LinkedIn
      URL: https://www.linkedin.com/search/results/all/?keywords=%23metarex
      identifier: LinkedIn
      pre: '<i class="linkedin icon"></i>'
      post: " 🦖"
      weight: 100
    - name: MetaRex on GitHub
      URL: https://github.com/orgs/metarex-media/repositories?q=sort%3Aname-asc
      identifier: GitHub
      pre: '<i class="github icon"></i>'
      post: " 🦖"
      weight: 110

    # - name:       See the IBC Winner
    #   URL:        /donate/
    #   identifier: cake
    #   pre:
    #   post:       " 🦖"
    #   weight:     110
    - name: Feed Rexy
      URL: /donate/
      identifier: cake
      pre:
      post: " 🍰"
      weight: 110
    - name: Try a demo
      URL: /app/demos/
      identifier: feed
      pre:  "⏯️ "
      post: " 🦖"
      weight: 120
# links to linkedin left & right

# --- Git ---------------------------------------------------------------------
# Will give values to .Lastmod etc.
enableGitInfo: true

# --- Taxonomies --------------------------------------------------------------
# Comment out to enable taxonomies in fohuw
# --- Taxonomies --------------------------------------------------------------
# Comment out to enable taxonomies in fohuw
# disableKinds: ["taxonomy", "taxonomyTerm"]

# ignore `tmp-` files in /content /data & i*ln
ignoreFiles:
  - \.tmp-$

# You can add your own taxonomies
# See params for how these are shown on pages
# https://gohugo.io/content-management/taxonomies/#what-is-a-taxonomy
taxonomies:
  tag: tags

# --- Permalink --------------------------------------------------------------
# Configure how URLs look like per section.
permalinks:
  blog: "/:section/:year/:month/:day/:slug/"

# --- Image processing --------------------------------------------------------
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: Smart

# --- Services ----------------------------------------------------------------
services:
  googleAnalytics:
    # Comment out the next line to disable GA tracking. Also disables the
    # feature described in [params.ui.feedback].
    #id: UA-00000000-0

# --- Language ----------------------------------------------------------------
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
# Useful when translating.
enableMissingTranslationPlaceholders: false
# Language configuration
languages:
  en:
    title: metarex.media
    languageName: English
    # Weight used for sorting.
    weight: 1
    params:
      description: Metadata Resource Express

# --- Markdown ----------------------------------------------------------------
markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # THIS MUST BE FALSE for mermaid to work!!!
    guessSyntax: false
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style: vs
    anchorLineNos: false
    codeFences: true
    lineAnchors: ""
    # hl_Lines:           1
    # lineNoStart:        1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

# --- Output formats ----------------------------------------------------------
# Comment out if you don't want the "print entire section" link enabled.
outputs:
  section:
    - HTML
    - RSS
