#                              _
#   ___  __ _   _ __    _ __  | |  ___
#  (_-< / _` | | '  \  | '_ \ | | / -_)
#  /__/ \__,_| |_|_|_| | .__/ |_| \___|
#                      |_|

# REMEMBER the dot in .gitpod.yml - use this file in a comparator

tasks:
  - before: echo "Please install clog"
  - init: echo "Please install clog"

# hugo port for server & godoc
ports:
  - port: 1313
    onOpen: open-browser
